name: City
version: 1.1.9
author: Maygo
main: fr.maygo.city.City
commands:
  cite:
    aliases: [spawn,hub,lobby]
  option:
    aliases: [options]
  roue:
  vanish:
  credit:
  house:
  setteam:
  inv:
  ec:
  info:
    aliases: [say,warning]